### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by huanghjA** [yuhuan-wu/JCS#1]
Hi, thanks for your share of JCS model. How can I access the training code?

**Comment by yuhuan-wu** [comment]
Thanks for your attention. The training code is still under preparation.
If available, in this week,  I will release the training code.

**Comment by tifat58** [comment]
Hi, Any update on training code? is it possible to release it soon. Thanks

**Comment by yuhuan-wu** [comment]
Hi, I have uploaded the training examples to this repository.
Plz run `git pull` and start to train our model with training examples:

`CUDA_VISIBLE_DEVICES=0 ./tools/train.sh`

**Comment by tifat58** [comment]
Thanks a lot :)

**Comment by yuhuan-wu** [comment]
It should not have training issues now. I decide to close this issue.

If you have any other questions, please discuss via creating a new issue.

Thanks :)
