### ISSUE TITLE
Where is 'dcm_png' folder in COVID-CS??

### ISSUE THREAD

**Issue by qlstn9150** [yuhuan-wu/JCS#4]

**Comment by yuhuan-wu** [comment]
Hello. The folder `dcm_png` contains original CT images, which are not released due to related policies. Instead, we have released the corresponding features for each CT image.

**Comment by qlstn9150** [comment]
Then, can't i run train.sh with 'COVID-CS' data?

example) 
train.sh ----data_dir ./data/COVID-CS

**Comment by yuhuan-wu** [comment]
since train.py code does not directly support training with stage-1 features, currently the answer is YES.
Testing with COVID-CS data has no problems.
