### ISSUE TITLE
How can i use the stage 1 feature in the code? thanks.

### ISSUE THREAD

**Issue by neverstoplearn** [yuhuan-wu/JCS#5]

**Comment by neverstoplearn** [comment]
where i need to change?

**Comment by yuhuan-wu** [comment]
set `input_features` of the backbone code to `True` so the network can be fed with the stage-1 features. 
Two places:
https://github.com/yuhuan-wu/JCS/blob/fa4bb6ae452c6aa042db8c762822e72df65d9519/Models/res2net.py#L122
https://github.com/yuhuan-wu/JCS/blob/fa4bb6ae452c6aa042db8c762822e72df65d9519/Models/vgg.py#L7

**Comment by neverstoplearn** [comment]
> set `input_features` of the backbone code to `True` so the network can be fed with the stage-1 features. Two places:
> 
> https://github.com/yuhuan-wu/JCS/blob/fa4bb6ae452c6aa042db8c762822e72df65d9519/Models/res2net.py#L122
> 
> 
> https://github.com/yuhuan-wu/JCS/blob/fa4bb6ae452c6aa042db8c762822e72df65d9519/Models/vgg.py#L7

thanks.
